SET NAMES utf8mb4;
CREATE TABLE `history` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `filename` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '文件名',
  `url` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'url',
  `size` INT(11) NOT NULL DEFAULT 0 COMMENT '文件大小',
  `mime` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '文件mime',
  `md5` VARCHAR(32) NOT NULL DEFAULT ''  COMMENT 'md5值',
  `upload_server` VARCHAR(16) NOT NULL DEFAULT ''  COMMENT '图床',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX inx_md5(md5) COMMENT 'md5字段普通索引'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='PicUploader上传历史记录';